import Head from "next/head";
import AppHeader from "@/components/header";
import { AppMain } from "./styles";
import { PropsWithChildren, useEffect } from "react";

export type AppLayoutProps = PropsWithChildren<{}>;

export default function AppLayout(props: AppLayoutProps) {
  useEffect(() => {
    document.body.classList.add("sticky-header");

    return () => {
      document.body.classList.remove("sticky-header");
    };
  }, []);

  return (
    <>
      <Head>
        <title>Disrobe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <AppHeader />
      <AppMain id="main">{props.children}</AppMain>
    </>
  );
}
