import Head from "next/head";
import AppHeader from "@/components/header";
import { AppMain, AppRoot } from "./styles";
import { PropsWithChildren } from "react";

export type AppLayoutProps = PropsWithChildren<{}>;

export default function AppLayout(props: AppLayoutProps) {
  return (
    <>
      <Head>
        <title>Disrobe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <AppRoot>
        <AppHeader position="relative" />
        <AppMain id="main">{props.children}</AppMain>
      </AppRoot>
    </>
  );
}
