import AppHeader from "@/components/header";
import Head from "next/head";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { PropsWithChildren } from "react";
import {
  SettingsMain,
  SettingsNavTab,
  SettingsTabs,
  TabContent,
} from "./styles";

const routes = [
  { label: "Account", path: "account" },
  { label: "Notifications", path: "notifications" },
];

export default function SettingsLayout(props: PropsWithChildren) {
  const pathname = usePathname();

  return (
    <>
      <Head>
        <title>Disrobe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <AppHeader />
      <SettingsMain>
        <SettingsTabs value={pathname} orientation="vertical">
          {routes.map((route) => (
            <SettingsNavTab
              key={route.path}
              value={`/settings/${route.path}`}
              href={`/settings/${route.path}`}
              label={route.label}
              component={Link}
            />
          ))}
        </SettingsTabs>
        <TabContent>{props.children}</TabContent>
      </SettingsMain>
    </>
  );
}
