import Head from "next/head";
import AppHeader from "@/components/header";
import { Main } from "./styles";
import { PropsWithChildren } from "react";

export type BlogLayoutProps = PropsWithChildren<{}>;

export default function BlogLayout(props: BlogLayoutProps) {
  return (
    <>
      <Head>
        <title>Disrobe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <AppHeader dynamicPosition />
      <Main id="main">{props.children}</Main>
    </>
  );
}
